# Generated by Django 2.2.6 on 2019-11-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
