# Generated by Django 2.2.6 on 2019-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='adv',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
