# Generated by Django 2.2.6 on 2019-11-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
