# Generated by Django 2.2.6 on 2019-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0002_auto_20191112_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='adv',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
