# Generated by Django 2.2.6 on 2020-06-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0003_auto_20200620_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True)),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
    ]
