# Generated by Django 2.2.6 on 2019-11-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0003_auto_20191112_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assoc',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('currently reading', 'currently reading'), ('not read', 'not read')], max_length=17),
        ),
    ]
