# Generated by Django 2.2.6 on 2019-11-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0004_auto_20191112_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
