# Generated by Django 2.2.6 on 2020-06-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_update_default_language'),
        ('silk_bookmarks', '0005_appearance_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Account')),
                ('photo_url', models.URLField(blank=True)),
            ],
            bases=('account.account',),
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='owner',
        ),
    ]
