# Generated by Django 2.2.6 on 2020-06-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silk_bookmarks', '0007_auto_20200623_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appearance',
        ),
    ]
