# Generated by Django 2.2.6 on 2020-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_account', '0003_auto_20200623_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='colour',
            field=models.CharField(default='#2e3235', max_length=50),
        ),
    ]
