# Generated by Django 2.2.6 on 2020-06-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_account', '0004_auto_20200623_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='user',
            new_name='owner',
        ),
    ]
