# Generated by Django 2.2.6 on 2020-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_account', '0005_auto_20200623_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='colour',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='photo_url',
            field=models.URLField(default='img/book2.jpg'),
        ),
    ]
