# Generated by Django 2.2.6 on 2020-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_account', '0006_auto_20200702_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='photo_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1512580770426-cbed71c40e94?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1982&q=80'),
        ),
    ]
